language: php

php:
  - 7.4

sudo: false

install:
  - travis_retry composer install

script:
  - composer validate --no-interaction
  - make phpunit
  - make cs
  - make phpmd

cache:
  directories:
    - $HOME/.composer/cache
